#!/bin/bash
# Frontend post-install setup script

echo "🎨 Poison Guard Frontend - Setup Complete!"
echo ""
echo "📦 Dependencies installed successfully"
echo ""
echo "🚀 Quick Start:"
echo "   npm run dev      - Start development server on http://localhost:3000"
echo "   npm run build    - Build for production"
echo "   npm run preview  - Preview production build"
echo ""
echo "📖 Documentation:"
echo "   - Frontend README: frontend/README.md"
echo "   - Setup Guide: FRONTEND_SETUP_GUIDE.md"
echo ""
echo "⚙️  Configuration:"
echo "   1. Ensure backend is running on http://localhost:8000"
echo "   2. Create .env.local with VITE_API_URL and VITE_API_KEY (optional)"
echo "   3. Run 'npm run dev' to start development server"
echo ""
echo "💡 API Key Management:"
echo "   - Set VITE_API_KEY environment variable, or"
echo "   - Provide via Settings page in the application"
echo ""
echo "🎯 Useful Endpoints:"
echo "   - Home: http://localhost:3000/"
echo "   - Dashboard: http://localhost:3000/dashboard"
echo "   - Chatbot: http://localhost:3000/chatbot"
echo "   - Settings: http://localhost:3000/settings"
echo ""
